# Generated by Django 5.0.4 on 2024-11-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Members',
        ),
    ]
